# Data Generator: Synthetic fraud data
import csv
import os
import random
import uuid

NARRATIONS = [
    "Invoice payment - textile goods",
    "Advance payment - saree consignment",
    "Pre-disbursement transfer",
    "Trade credit settlement",
    "Supplier advance - fabric order",
]

NAME = [
    "Ramesh Gupta",
    "Sunita Devi",
    "Arjun Mehta",
    "Priya Nair",
    "Vikram Joshi",
    "Anita Sharma",
]

ACCOUNT_TYPE = ["Savings", "Current", "Overdraft"]


# data generating function
def generate_transactions():
    # indian numbers start with 6,7,8,9 so to generate a random indian number
    first_digit = random.choice(["6", "7", "8", "9"])
    remaining = str(random.randint(100000000, 999999999))
    mobile_number = first_digit + remaining

    return {
        "Transaction_ID": str(uuid.uuid4()),
        "Narration": random.choice(NARRATIONS),
        "Pincode": str(random.randint(110000, 999999)),
        "MobileNumber": mobile_number,
        "Name": random.choice(NAME),
        "AccountNumber": str(random.randint(100000000000, 999999999999)),
        "AccountType": random.choice(ACCOUNT_TYPE),
    }


transactions = [generate_transactions() for _ in range(10)]

for t in transactions:
    print(t)


# generating/Creating a csv file and storing the data generated by the above code
os.makedirs("data/synthetic", exist_ok=True)

with open("data/synthetic/transactions.csv", "w", newline="") as f:
    writer = csv.DictWriter(
        f, fieldnames=transactions[0].keys()
    )  # making the keys of the dict to fieldnames/headers
    writer.writeheader()
    writer.writerows(transactions)

print("\nSaved to data/synthetic/transactions.csv")
